Algoritmo "exercicio_se_condicionalSimples_01"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 



Var
x,y: inteiro


Inicio
escreval("Insira dois valores: ")
leia(x)
leia(y)

      se x >= y entao
         escreva("O maior valor é: ", x)
      fimse
      
      se y > x entao
          escreva("O maior valor é: ", y)
      fimse



Fimalgoritmo
