Algoritmo "matriz_alfabeto"

Var
i, j: inteiro
matrizAlfabeto: vetor[10..13,33..36] de caracter

Inicio

matrizAlfabeto[10,33] <- "A"
matrizAlfabeto[10,34] <- "B"
matrizAlfabeto[10,35] <- "C"
matrizAlfabeto[10,36] <- "D"
matrizAlfabeto[11,33] <- "E"
matrizAlfabeto[11,34] <- "F"
matrizAlfabeto[11,35] <- "G"
matrizAlfabeto[11,36] <- "H"
matrizAlfabeto[12,33] <- "I"
matrizAlfabeto[12,34] <- "J"
matrizAlfabeto[12,35] <- "K"
matrizAlfabeto[12,36] <- "L"
matrizAlfabeto[13,33] <- "M"
matrizAlfabeto[13,34] <- "N"
matrizAlfabeto[13,35] <- "O"
matrizAlfabeto[13,36] <- "P"

para j de 33 ate 36 faca
   escreva(matrizAlfabeto[12,j], " ")
fimpara

Fimalgoritmo
